# -*- coding: utf-8 -*-
"""AllCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EYG2II1LXTfrPNt_RCmj4dMVkvtA-2Py
"""



X = (int(input("Ingrese el valor de X")))

resultado = (X**2)+3*X+1/4

print(f"El resultado de la ecuacion es: {resultado}")

"""# Nueva sección"""

nombre = input("Ingrese su nombre ")
Rut = input("Ingrese su rut ")
Correo = input("Ingrese su correo ")
telefono = input("Ingrese su N° telefonico ")

print(f"NOMBRE:\t\t{nombre}")
print(f"RUT:\t\t{Rut}")
print(f"Correo:\t\t{Correo}")
print(f"Telefono:\t{telefono}")

a = 12
b = 12
if a > b:
    print("a es mayor que b")
elif a < b:
    print("b es igual o mayor que a")
else:
    print("a y b son iguales")

print("Hola a todos \n soy informatico")

i = input("Ingrese su nombre ")
t = input("Ingrese su apellido ")
e = int(input("Ingrese su edad "))

print(f"su nombre es {i} {t} y su edad actual es {e}")

print("hol\ta \t  todos\t\tsoy informatico")

b = (int(input("Ingrese su edad ")))

if b >= 18:
    print("Usted es mayor de edad")
elif b <= 17:
    print("Usted es menor de edad")

7
5
nota1 = (float(input("Ingrese la primera nota ")))
if nota1 >= 7.1:
  print("Ingrese una nota valida")
nota2 = (float(input("Ingresa la segunda nota ")))
if nota1 >= 7.1:
  print("Ingrese una nota valida")
nota3 = (float(input("Ingresa la Tercera nota ")))
if nota1 >= 7.1:
  print("Ingrese una nota valida")

promedio = (nota1+nota2+nota3)/3

if promedio >= 4:

  print(f"su nota final es {promedio} por lo cual esta Aprobado")

elif promedio <= 3.9:

  print(f"su nota final es {promedio} por lo cual esta Reprobado")

numero = (int(input("Ingrese un numero ")))

for i in range(1,11):
  resultado = i * numero
print(i,"X",numero,"=",i*numero)

print("¿Cual de los siguientes animales vive en el agua?")

print("1 : Perro")
print("2 : Cocodrilo")
print("3 : conejo")
print("4 : tiburon")

r1 = (str(input("Ingrese su respuesta ")))

if r1 == "perro":
  print(f"su respuesta fue {r1} la cual le da 0 puntos")

elif r1 == "cocodrilo":
  print(f"su respuesta fue {r1} la cual le da +0,5 puntos")

elif r1 == "conejo":
  print(f"su respuesta fue {r1} la cual le da 0 puntos")

elif r1 == "tiburon":
  print(f"su respuesta fue {r1} la cual le da +1.0 puntos")

usuario = input("Ingrese su usuario: ")
password = input("Ingrese su password: ")

if usuario == "pedro" and password == "1234":
    print("Pedro se ha conectado")
elif usuario == "angel" and password == "a4s1":
    print("Angel se ha conectado")
else:
    print("El usuario y password son invalidos")

puntaje = 0

print("¿Como se llama el brujo principal en los libros de The Witcher?")

print("1 : Geralt")
print("2 : Geralt de Rivia")
print("3 : Asimov")
print("4 : Gandalf")

r1 = (str(input("Ingrese su respuesta ")))

if r1 == "geralt":
  print(f"su respuesta fue {r1} la cual le da 1 puntos")
  puntaje += 1
elif r1 == "geralt de rivia":
  print(f"su respuesta fue {r1} la cual le da 5 puntos")
  puntaje += 5

elif r1 == "asimov":
  print(f"su respuesta fue {r1} la cual le da 1 puntos")
  puntaje += 1
elif r1 == "gandalf":
  print(f"su respuesta fue {r1} la cual le da 1 puntos")
  puntaje += 1

print("¿como se llama el autor de Yo Robot?")

print("1 : pablo neruda")
print("2 : isaac asimov")
print("3 : harry potter")
print("4 : ivan el gordo")

r2 = (str(input("Ingrese su respuesta ")))

if r2 == "pablo neruda":
  print(f"su respuesta fue {r2} la cual le da 1 puntos")
  puntaje += 1
elif r2 == "harry potter":
  print(f"su respuesta fue {r2} la cual le da 1 puntos")
  puntaje += 1
elif r2 == "isaac asimov":
  print(f"su respuesta fue {r2} la cual le da 5 puntos")
  puntaje += 5
elif r2 == "ivan el gordo":
  print(f"su respuesta fue {r2} la cual le da 1 puntos")
  puntaje += 1

print("¿como se llama la pelicula de magos mas famosa del mundo?")

print("1 : star wars")
print("2 : harry potter")
print("3 : jurassic park")
print("4 : hunger games")

r3 = (str(input("Ingrese su respuesta ")))

if r3 == "star wars":
  print(f"su respuesta fue {r3} la cual le da 1 puntos")
  puntaje += 1
elif r3 == "jurassic park":
  print(f"su respuesta fue {r3} la cual le da 1 puntos")
  puntaje += 1
elif r3 == "harry potter":
  print(f"su respuesta fue {r3} la cual le da 5 puntos")
  puntaje += 5
elif r3 == "hunger games":
  print(f"su respuesta fue {r3} la cual le da 1 puntos")
  puntaje += 1


print(f"su puntaje final es de {puntaje}")

print("Eliga una opcion")
print("1 - Dolar Autraliano a Peso")
print("2 - Peso Argentino a peso Chileno")
print("3 - Yen a pesos Chilenos")

dolara=605.64
pesoa=7.21
yen=6.35

opcion=(int(input("Eliga una opcion ")))

if opcion==1:
    dolar=input("Ingrese cuantos dolares ")

    print(f"cantidad {dolar} dolar Australiano a pesos Chilenos es igual a {opcion*dolara} ")
elif opcion==2:
    peso=(int(input("Ingrese la cantidad de pesos a convertir")))
    print(f"cantidad {peso} pesos Argentinos a pesos Chilenos es igual a {peso*pesoa} ")

else:
    opcion==3
    yens=(int(input("Ingrese la cantidad de yenes a convertir")))
    print(f"cantidad {yens} yenes a pesos Chilenos es igual a {yens*yen} ")

#VENTA DE ZAPATOS

zapato = 20000
despacho = 3000

venta = (int(input("Ingrese la cantidad de que desea ")))

if venta == 1:
    print(f"El valor a cancelar es de {zapato} mas el despacho ${despacho}, total ${zapato+despacho}")

else:
    print(f"El valor a cancelar es de ${venta*zapato} el despacho es gratis.")

num1 = (int(input("Ingrese el primer numero ")))
num2 = (int(input("Ingrese el segundo numero ")))
num3 = (int(input("Ingrese el tercer numero ")))

acumulador=0
contador=0

if num1 > 0 and num1 %2 == 0:
    acumulador = acumulador + num1
else:
    contador = contador + 1


if num2 > 0 and num2 %2 ==0:
     acumulador= acumulador + num2
else:
     contador = contador + 1


if num3 > 0 and num3 %2 ==0:
     acumulador = acumulador + num3
else:
     contador = contador + 1

print(f"valor de acumulador {acumulador}")

print(f"valor de contador {contador}")

#incompletooooooooo
numero = input("Ingrese un numero ")

Largotexto= len(numero)

print(Largotexto)

agua=600
azucar=1200
aceite=1500
arroz=1250
fideos=790
bebida=1780
chocolate=2500
panmolde= 1340

contador=0
acumulador=0

print("1- Agua")
print("2- Azucar")
print("3- Aceite")
print("4- Fideos")
print("5- Bebida")
print("6- Chocolate")
print("7- Pan de molde")
producto=(int(input("Eliga un producto ")))

if producto==1:
  contador= (int(input("Ingrese la cantidad de agua que lleva ")))
print(f"usted lleva {contador} el cual da un total {agua*contador}")

for numero in range(1, 20):
    if(numero % 2 != 0):
        print(numero)

num1 = (int(input("Ingrese el primer numero ")))
num2 = (int(input("Ingrese el segundo numero ")))
num3 = (int(input("Ingrese el tercer numero ")))


if num1 > num2 and num1 > num3:
    print(f"El numero mayor es {num1}")

     
    
if num2 > num1 and num2 > num3:
    print(f"El numero mayor es {num2}")

       

if num3 > num2 and num3 > num1:
    print(f"El numero mayor es {num3}")

if num1 == num2 and num2 == num3:
    print("todos son iguales")

print("Datos")

nombre = str(input("Ingrese su nombre "))
edad = int(input("Indique su edad "))
genero = str(input("Indique su Genero 1 - Maculino o 2 - Femenino "))
masculino = "1"
femenino = "2"
numt = int(input("Indique su numero de telefono "))

if genero=="1":
    print(f"su nombre es {nombre} y su edad es {edad}")
else:
    print(f"Su nombre es {nombre} y su numero de telefono es {numt}")

numero = (int(input("Ingrese un numero ")))

for i in range(1,11):
    print(i,"X",numero,"=",i*numero)



print ("---------------------------------")
print (" Identificaciones para mascotas")
print ("---------------------------------")
print ("Tamaño de las placas")
print ("1.Pequeña $1500")
print ("2.Mediana $4500")
print ("3.Grande $5500")

ppequeña=1500
pmediana=4500
pgrande=5500

despacho=2000

acumulador=0

tidp1=0
tidp2=0
tidp3=0

print ("---------------------------------")
idp=int(input("Seleccione el tamaño de la placa "))

if idp==1:
    cant1=int(input("Ingrese la cantidad a comprar "))
    tidp1=cant1*ppequeña
    acumulador=tidp1+acumulador 

if idp==2:
    cant2=int(input("Ingrese la cantidad a comprar "))
    tidp2=cant2*pmediana
    acumulador=tidp2+acumulador

if idp==3:
    cant3=int(input("Ingrese la cantidad a comprar "))
    tidp3=cant3*pgrande
    acumulador=tidp3+acumulador 

if acumulador >= 10000:
    print(f"El valor a cancelar es ${acumulador}. Por compras sobre $10.000, el envío es gratis.")
   
else: 
    print(f"El valor a cancelar es ${acumulador} más el envío ${despacho}. Total: ${acumulador+despacho}")

print ("---------------------------------")
print ("     Automotora")
print ("---------------------------------")
print ("Tipo de revisión")
print ("1.Frenos $1500")
print ("2.Aceite $1000")
print ("3.Motor $2000")
print ("4.Luces $3000")

frenos=1500
aceite=1000
motor=2000
luces=3000

acumulador=0


rfrenos=int(input("¿Desea realizar revisión de los frenos? 1.Si / 2.No "))
if rfrenos==1:
    acumulador=frenos+acumulador

raceite=int(input("¿Desea realizar revisión del aceite? 1.Si / 2.No "))
if raceite==1:
    acumulador=aceite+acumulador 

rmotor=int(input("¿Desea realizar revisión del motor? 1.Si / 2. No "))
if rmotor==1:
    acumulador=motor+acumulador 

rluces=int(input("Desea realizar revisión de las luces? 1.Si / 2.No "))
if rluces==1:
    acumulador=luces+acumulador


cupondescuento=int(input("Es su auto marca Toyota o Mazda? 1.Si / 2.No "))
if cupondescuento==1:
   acumulador=acumulador-(acumulador*10/100)
   print("-------------------------")
   print(f"El total a cancelar, con descuento aplicado, es ${acumulador}.") 
else:
   print("-------------------------")
   print(f"El total a cancelar es ${acumulador}.")

a = 0
while a < 5:
    print (a)
    a = a + 1

fact = 1

i = 1

num = int(input("Ingrese un numero   "))
while i <= num:
    fact = fact * i
    i = i + 1
print(f"El factorial de {num} es: {fact}")

frase = "Hola mundo"
for caracter in frase:
    print(caracter)

num = 1
suma = 0
total=0

while num <= 5:
    suma = int(input("Ingrese un numero    "))

  

    total = total + suma

    num = num + 1

print(total)

for n in range(1,11):
    for i in range (1,11):

        print(f"{n} X {i }= {n*i}")
    print("")

nombre = input("Ingresa tu nombre")

for c in nombre:
    print(c)

numero = int(input("Ingresa un numero"))

while numero < 0:
    print("ERROR!!     debe ingresar un numero mayor a 0")
    numero=int(input("Debe volver a ingresar un numero"))

pliviano=1000
pnormal=4500
ppesado=8000

cantp1=0
cont1=0
cantp2=0
cont2=0
cantp3=0
cont3=0


print("-----------------")
print("   ENCOMIENDAS") 
print("-----------------")
n=int(input("Ingrese la cantidad de paquetes: "))

paquete=range(1,n+1)
for n in paquete:
    cant=int(input("Ingrese el peso del paquete:\n "))
    if cant >=0 and cant <=5: 
        cantp1=cantp1 + pliviano
        cont1=cont1+1
        
    elif cant >=6 and cant <=10:
        cantp2=cantp2 + pnormal
        cont2=cont2+1
        
    elif cant >=11 and cant <=20:
        cantp3=cantp3 + ppesado
        cont3=cont3+1


total=cantp1+cantp2+cantp3


print("          ENCOMIENDAS") 
print("--------------------------------")
print(f"{cont1} bulto LIVIANO:\t${cantp1}")
print(f"{cont2} bulto NORMAL:\t${cantp2}")
print(f"{cont3} bulto PESADO:\t${cantp3}")
print("--------------------------------")
print(f"\tTotal: {total}")

print("ENCOMIENTAS")

#pesos
l=1000 #livino
n=4500 #normal
p=8000 #pesado


cant1=0
cantt1=0
cant2=0
cantt2=0
cant3=0
cantt3=0

total=0

cant=int(input(f"Cuantos paquetes desea llevar:  " ))

for cant in range(0,3):
    peso=int(input("Cuanto pesa el bulto:   "))
    if peso >= 0 and peso <= 5:
        cantt1=cantt1+l
        cant1=cant1+1

    elif peso >= 6 and peso <= 10:   
        cantt2=cantt2+n
        cant2=cant2+1

    elif peso >= 11 and peso <= 20:
        cantt3=cantt3+p
        cant3=cant3+1

     
total=cantt1+cantt2+cantt3

print("ENCONIENDAS")
print("-----------------------------")

print(f"{cant1} bulto LIVIANO: ${cantt1}")
print(f"{cant2} bulto NORMAL: ${cantt2}")
print(f"{cant3} bulto PESADO: ${cantt3}")

print("-----------------------------")

print(total)

a = 5
b = 0 

try:
    c = a/b
    print(f"El resultado es {c}")
except:
    print("No se a podido realizar la division")

try:
    numero = int(input(f"Ingrese un numero:  \n  "))
except:
    print("El dato es incorrecto")
else:
    print(f"su numero es {numero}")

flagDatoCorrecto = False

while flagDatoCorrecto == False:
    try:
        numero = int(input("Ingrese un numero"))
    except:
        print("El numero es incorrecto")
    else:
        flagDatoCorrecto = True
print(numero)

flagDatoCorrecto = False

while flagDatoCorrecto == False:
    try:
        numero = int(input("Ingrese un numero, entre 1 y 10:  "   ))

    except:
        print("El numero es incorrecto")
    else:
        if numero >=1 and numero <= 10:
            flagDatoCorrecto = True
        else:
            print("El numero debe estar entre el 1 al 10")    
print(numero)



opcion = 1


while opcion >0 and opcion <3:
    print("1.- Opcion 1")
    print("2.- Opcion 2")
    print("3.-  Salir")

    opcion= int(input("Seleccion la opcion correcta"))

    if opcion ==1:
        print("Usted selecciono la opcion 1"  )
    elif opcion == 2:
        print("Opcion 2 seleccionada")
    elif opcion == 3:
        print("saliendo.....")
    else:
        print("Opcion invalida.") 
        opcion=1

def contar_vocales(cadena):
	contador = 0
	for letra in cadena:
		if letra.lower() in "aeiou":
			contador += 1
	return contador

cadena = str(input("Ingrese una palabra para contar las vocales: "   ))
cantidad = contar_vocales(cadena)
print(f"En la cadena '{cadena}'' hay {cantidad} vocales")

def contar_vocales(cadena):
	contador = 0
	for letra in cadena:
		if letra.lower() in "aeiou":
			contador += 1
	return contador

cadena = str(input("Ingrese una palabra para contar las vocales: "   ))
cantidad = contar_vocales(cadena)

if cantidad <=2:
    print("perdio")
elif cantidad <=5:
    print("Casi gana")
elif cantidad >=5:
    print("Gano un chocman")

palabra = input("Ingrese una palabra")
cantidadVolcales = 0

for caracter in palabra:
    if caracter in "aeiou":
        cantidadVolcales = cantidadVolcales + 1

print(f" la cantidad de vocales es {cantidadVolcales} ")


if cantidadVolcales <=2:
    print("Usted es un perdedor")
elif cantidadVolcales >=3 and cantidadVolcales <=5:
    print("Usted casi no es un perdedor")
elif cantidadVolcales >=6:
    print("Usted es un ganador")

usuario1= "itamayo"
password1= "12345"

usuario2=None
password2=None

opcion=1

while opcion >0 and opcion <3:
    print("1.- Iniciar Sesion")
    print("2.- Registrar usuario")
    print("3.- Salir")

    opcion= int(input(f"Seleccion una opcion:  \n "  ))

    if opcion ==1:
        usuario=str(input(f"Ingrese su usuario:  \n  "))
        if usuario==usuario1:
            print("usuario valido")  
            password=str(input(f"ingrese su contraseña:  \n  "))  
            password==password1
            print("inicio de secion correcta")
    elif opcion ==2:
            usuario2=str(input(f"Indique su nombre de usuario:   \n "))
            print(f"usuario {usuario2} registrado")
            password2=str(input(f"Cual sera su contraseña:   \n  "))
            print("password registrada")
    elif opcion ==3:
            print("usted salio del sistema")
               
    while opcion >0 and opcion <3:
        print("1.- Realizar llamada")
        print("2.- Enviar correco electronico")
        print("3.- Cerrar sesion")            

        opcion= int(input(f"Seleccion una opcion:    \n   "  ))
                
        if opcion == 1:
            numt=int(input(f"Marque el numero telefonico:     \n    "))

lista = [1,"Hola",20,"adiossss"]
lista.append(3.14)                    #agregar un elemento a final.
lista.extend(["saturno",00.10])       #agregar mas de un elemento .
lista.insert(1,1313)                  #agregar un elemento donde uno guste.
lista.remove                          #elimina un elemento de la lista.
lista.reverse                         #invierte la lista.
lista.sort                            #ordenar de mayor a menor.
lista.pop                             #elimina el ultimo elemento de la lista.
print(lista[1])

lista1 = []
opcion = 1

while opcion >0 and opcion <4:
    print("MENU")
    print("1.- Agregar un nombre a la lista")
    print("2.- Listar nombres")
    print("3.- Eliminar todos los nombres")
    print("4.- Salir")

    opcion = int(input("Seleccione la opcion.."))

    if opcion==1:
        nombre = input("Ingrese un nombre")
        lista1.append(nombre)

    elif opcion == 2:
        for a in lista1:
            print(a)
    elif opcion == 3:
        lista1.clear()
        print("Se eliminaron todos los nombres de la lista")
       
    elif opcion == 4:
        print("Saliendo de la aplicacion..")
    else:
        print("Opcion inválida!")
        opcion = 1

print("Adios")

lista=[]


opcion = 1

while opcion >0 and opcion <2:
    print("MENU")
    print("1.- Agregar un numero a la lista")
    print("2.- mostrar los datos guardados.")
    

    opcion = int(input("Seleccione la opcion.."))
  
    if opcion==1:
        num = int(input("Ingrese un numero"))
        for i in range(1,11):
            resultado=(i*num)
            lista.append(resultado)

       

    elif opcion == 2:
       for i in lista:
        print(i)

lista=[]

numero=1

while numero !=0:

    numero =int(input("Ingrese un numero"))

    if numero > 0:
        lista.append(numero)

lista.sort
print(lista)

lista = []


suma = 0

for x in range(1,11):

    numero = int(input("Ingrese un numero"))
    lista.append(numero)

    suma = suma + numero

print(f" El promedio es {suma/10}")
print(lista)

nombres = []
apellidos = []

for x in range(1,4):
    nombre = input("Ingrese un nombre")
    nombres.append(nombre)

    apellido = input("Ingrese un apellido")
    apellidos.append(apellido)

for x in range(0,3):

    print(f" nombre: {nombres[x]} {apellidos[x]}")

lista = []
nombreLargo = ""
for x in range(1,4):
    nombre = input("Ingrese un nombre")
    lista.append(nombre)

    nombreActual = nombre

    if len(nombreActual) > len(nombreLargo):
        nombreLargo = nombre

print(nombreLargo)

correo=str(input("Ingrese su correo: "))
        print(correo.find("@"))
        correolist.append(correo)

listaRut=[]
listName=[]
listMail=[]
listEdad=[]
listFecha=[]
listComensales=[]

opcion=1

while opcion >0 and opcion <4:
    print("1.- Registrar Cliente")
    print("2.- Registro de reserva")
    print("3.- consultar cliente")
    print("4.- Salir")
    
    opcion=int(input(f"Eliga una opcion      \n    "))
    
    if opcion == 1:
        
        flagDatoCorrecto=False
        while flagDatoCorrecto==False:
            try:
                rut=int(input(f"Ingrese su rut   \n    "))
                listaRut.append(rut)
            except:
                  print("Rut Incorrecto")
            else:      
                if rut > 5000000 and rut < 99999999:
                      flagDatoCorrecto=True
                else:
                    print("Dato invalido")    
                      
        name=str(input(f"Ingrese su nombre:      \n    "))
        listName.append(name)
         
        mail=str(input(f"Ingrese su Mail            \n "))
        print(mail.find("@"))
        listMail.append(mail)      
        
        flagDatoCorrecto=False
        while flagDatoCorrecto==False:
            try:
                edad=int(input(f"Ingrese su edad       \n "))
                listEdad.append(edad)     
            except:
                print("Edad Invalida")
            else:
                if edad >18 and edad <110:
                    flagDatoCorrecto=True
                else:
                    print("La edad indicada debe ser entre 18 y 110 años")  
                              
        print("---------Cliente Registrado Exitosamente-----------") 
    
    if opcion == 2:
        
        reserva=1
        while reserva>0 and reserva <2:
            print("Desea hacer una reserva?")
            print("1.- Si  ")
            print("2.- No  ")
            reserva=int(input(f"Desea una reserva?      \n     "))
            
            if reserva==1:    
                rut01=int(input(f"Ingrese el rut registrado     \n    "))
                
                if rut01 in listaRut:
                    print("Usuario registrado")
                else:
                    print("Usuario No registrado")
                
                fechaReserva=str(input(f"Ingrese la fecha de la reserva:     \n "))      
                listFecha.append(fechaReserva)   
                
                reservaComensales=int(input(f"Ingre la cantidad de Comensales       \n     "))                                 
                listComensales.append(reservaComensales)
                
                print("---Reserva Guardada Exitosamente----")
                print(f"{listFecha}_{listComensales}comensales.")
    
    if opcion ==3:
        rut02=int(input("Ingrese el Rut del cliente a consultar"))
        if rut02 in listaRut:
            for i in range(len(listaRut)):
                if rut02==listaRut[i]:
                    print(f" Rut: {listaRut[i]}\nNombre: {listName[i]} \n Edad: {listEdad[i]}  \n Correo: {listMail[i]} \n Fecha de reserva: {listFecha[i]} \n Cantidad de comensales: {listComensales[i]}")
    
    if opcion==4:
        print("---------Cerrando sesion----------")

namelist=[]
rutlist=[]
correolist=[]
edadlist=[]
fechalist=[]
comensaleslist=[]

opcion=1
while opcion >0 and opcion <4:
    print("1.-Registrar Cliente ")
    print("2.- Registro de Reserva ")
    print("3.-Consultar Cliente Registrado")
    print("4.- Salir")
    
    opcion = int(input(f"Selecione una opcion \n"))
    
    if opcion ==1:
        flagsDatoCorrecto=False
        while flagsDatoCorrecto==False:
            try:
                name=str(input(f"Ingrese su nombre  \n "))
                namelist.append(name)
            except:
                  print("Nombre Incorrecto")                                                                     
            else:
                if name.isalpha():
                    flagsDatoCorrecto=True
                else:
                    print("El dato ingresado no es valido vuelva intentar")
                    
        flagsDatoCorrecto=False
        while flagsDatoCorrecto==False:
            try:
                rut=int(input(f"Ingrese su Rut   \n "))
                rutlist.append(rut)
            except:
                  print("Dato invalido")
            else:
                if rut >5000000 and rut <99999999:
                    flagsDatoCorrecto=True
                else:
                    print("Debe ingresar su rut sin puntos ni codigo verificados.")
        
        flagsDatoCorrecto=False
        while flagsDatoCorrecto==False:
            try:
                correo=str(input(f"Ingrese su Correo   \n "))
                correolist.append(correo)
            except:
                  print("Dato invalido")
            else:
                if "@" in correo:
                    flagsDatoCorrecto=True
                else:
                    print("ingrese su correo completo por favor.")
                    
        flagsDatoCorrecto=False
        while flagsDatoCorrecto==False:
            try:
                edad=int(input(f"Ingrese su edad   \n "))
                edadlist.append(edad)
            except:
                  print("Dato invalido")
            else:
                if edad>18 and edad <110:
                    flagsDatoCorrecto=True
                else:
                    print("la edad indicada debe estar entre 18 y 110 años")            
    
    if opcion == 2:
        
            
        rut01=int(input(f"Ingrese el rut del cliente  \n"))
                
        if rut01 in rutlist:
            print("Rut registrado")            
        else:
            print("Rut No registrado")
                
               
        fecha=str(input(f"ingrese la fecha en que desea reservar en formato YYYY-MM-DD   \n "))
        fechalist.append(fecha)
                
                    
           
        comensales=int(input(f"Ingrese la cantidad de comensales   \n "))
        comensaleslist.append(comensales)
               
                    
        print("---------Reserva guardada exitosamente----------")
        print(f"{fechalist}_{comensaleslist}")
            
            
                
    if opcion == 3:
        consultarRut=int(input(f"Ingrese el Rut del cliente a consultar      \n"))
        if consultarRut in rutlist:
            for i in range(len(rutlist)):
                if consultarRut==rutlist[i]:
                    print("-------DATOS DEL CLIENTE----")
                    print(f"Nombre: {namelist[i]}")
                    print(f"Rut: {rutlist[i]}")
                    print(f"Correo: {correolist[i]}")
                    print(f"Edad : {edadlist[i]}")
                    print(f"Fecha: {fechalist[i]}")
                    print(f"Comensales: {comensaleslist[i]}")
                    print("......................................................")
                    print("......................................................")
    
    if opcion== 4 :
        print("------------Cerrando Sesion------------")

import numpy as np

arreglo = np.array([1,2,3,4])

print(arreglo)

print(arreglo.ndim)

print(len(arreglo))

#EJERCICIO 1

import numpy as np 
import random as r

#r.randrange
#numaleatorio=(r.randrange(0,100))


arreglo10=[r.randrange(0,100) for i in range (10)]
arreglo=np.array(arreglo10)

print(arreglo10)

#EJERCICIO 2

arreglocopiado=arreglo[:].copy()

print(arreglocopiado)

mayor=0 
menor = 100
suma=0
promedio=0

for i in arreglocopiado:


    if i > mayor:
        mayor=i
    
    if i < menor:
        menor=i

    suma = suma + i 

    promedio = suma/10 

    

print(f"El número mayor es {mayor}")
print(f"El número menor es {menor}")
print(f"La suma de los números es {suma}")
print(f"El promedio de los números es {promedio} ")

import numpy as np
import random as r


arregloejemplo = np.array([3,4,8,2,1])

arreglocopia=arregloejemplo[:].copy()

print(arreglocopia)

#suma de los elementos del arreglo
print(arreglocopia.sum())

#multiplicación uno por uno de los elementos
arreglocopia=arreglocopia*2
print(arreglocopia)

import numpy as np
import random as r


arregloA=np.array([r.randrange(0,500) for i in range (0,100)]) 
print(arregloA)

from tkinter import X
import numpy as np
import random as rn



arreloA= np.array([rn.randrange(1,7) for i in range(0,4)])

mayor = 0

indiceMayor = 0

print(arreloA)

for x in range(len(arreloA)):
    if(x % 2 == 0):
        print(f"INDICE : {x}")
        print(arreloA[x])

    if(arreloA[x] > mayor):
        mayor=arreloA[x]
        indiceMayor = x


arregloB=arreloA[:].copy()
print(arregloB)
arregloB = arregloB * 3

print(arreloA.sum() / len(arreloA))

print(arregloB)


print(f"El numero mayor {mayor} y su indice Mayor es el {indiceMayor}")

import numpy as np
import random as rm

arreglo = np.array([[rm.randrange(0,100) for i in range (0,3)],[rm.randrange(0,100) for i in range (0,3)]])

arreglo2 = np.array([ [rm.randrange(0,100) for i in range (0,5)] for i in range(0,50) ])

#print(arreglo)
print(arreglo2)

import numpy as np
import random as rm

arreglo = np.array([[rm.randrange(0,100) for i in range (0,3)],[rm.randrange(0,100) for i in range (0,3)]])

arreglo2 = np.array([ [rm.randrange(0,100) for i in range (0,3)] for i in range(0,3) ])

#print(arreglo)

print(arreglo2)

print(f"El promedio de todos los elementos es {arreglo2.mean()}")
print(f"La suma de la matriz es {arreglo2.sum()}")
print(f"Obtener la diagonal {arreglo2.diagonal()}")

import numpy as np
import random as rm

bus1 = np.zeros((10,4))

#print(bus1)

correlativo=1

for x in range(len(bus1)):
    for i in range(len(bus1[x])):
        bus1[x,i]=correlativo
        correlativo=correlativo+1

print(bus1)

import numpy as np
import random as rm

matriz = np.array([[rm.randrange(0,100) for i in range (0,4)] for i in range (0,4)])

print(matriz)
print(matriz.shape)

for x in range(matriz.shape[0]):
    print(f"la suma de las filas {x} {matriz [x , :].sum()}")
print("-------------------------------------------------------")
for i in range(matriz.shape[1]):
    print(f"la suma de las filas {i} {matriz [:,i].sum()}")

print(matriz.diagonal())
print(matriz.diagonal().sum())

import numpy as np
import random as rm


matriz=np.array([[chr(rm.randrange(97,122)) for x in range(0,4)] for i in range(0,4)])

print(matriz)


cantidadVocales=0
for x in range(matriz.shape[0]):
    for i in range(len(matriz[x])):
            print(matriz[x,i])
            if matriz[x,i]  in "aeiou":
                cantidadVocales=cantidadVocales+1

print(f"La cantidad de vocales es {cantidadVocales}")

import numpy as np
import random as rm

matriz = np.array([[rm.randrange(0,100) for i in range (0,4)] for i in range (0,4)])

print(matriz)
print(matriz.shape)

for x in range(matriz.shape[0]):
    print(f"la suma de las filas {x} {matriz [x , :].sum()}")
print("-------------------------------------------------------")
for i in range(matriz.shape[1]):
    print(f"la suma de las filas {i} {matriz [:,i].sum()}")

contadorImpar=0
for x in range(matriz.shape[0]):
    for i in range(len(matriz[x])):
        if(matriz[x,i] % 2 != 0):
            contadorImpar=contadorImpar+1
print(matriz)
print(f"{contadorImpar}")


#print(matriz.diagonal())
#print(matriz.diagonal().sum())

def saludo(nombre):
    print(f"Buenas Noches {nombre}")

name=str(input(f"Ingrese su nombre \n "))  

saludo(name)

def descuento(precio, descuento):

   

    totalDescuento= precio * (desto /100)
    print(f"El precio es {precio}")
    print(f"El descuento es {totalDescuento}")
    print(f"El total a pagar {precio-totalDescuento}, {totalDescuento}")

desto = int(input(f"Ingrese el descuento \n"))
precio = int(input(f"Ingrese el precio del producto \n")) 
   

descuento(precio,desto)

def calcularIMC(peso,estatura):
    imc= peso / (estatura**2)
    print(imc)
    if imc < 18.5:
        print("Bajo peso")
    elif imc < 24.9:
        print("peso Adecuado") 
    elif imc < 29.9:
        print("Sobre peso")
    elif imc < 34.9:
        print("Obecidad grado 1")
    elif imc < 39.9:
        print("Obecidad grado 2")
    else:
        print("Obecidad grado 3")    

estatura=float(input("Ingrese su estatura"))
peso=int(input("Ingrese su peso"))
calcularIMC(peso,estatura)

def es_primo():
    for n in range(2, num):
        if num % n == 0:
            print("No es primo", n, "es divisor")
            return False
    print("Es primo")
    return True


def factorial():
    total=0
    for x in range(1,num0+1):
        if total == 0:
            total=x
        else:    
            total= total*x
    print(f"el factorial de {num0} es {total}")



def palindrome(palabra):
    palabraAlrevez= ""
    for x in palabra:
        palabraAlrevez= x*palabraAlrevez

    print()    





opcion=1
while opcion >0 and opcion <4:
    print("1.-Numero Primo ")
    print("2.- Factorial ")
    print("3.-Palindrome")
    print("4.- Salir")
    
    opcion = int(input(f"Selecione una opcion \n"))

    if opcion==1:
        num=int(input(f"Ingrese un numero  \n"))
        es_primo()

    if opcion==2:
        num0=int(input(f"Ingrese un numero para calcular su factorial \n"))
        factorial()

def NumPrimo():
    for n in range (2,num1):
        if num1 % n ==0:
            print(f"El número {num1} no es primo")
            return False
    print(f"El número {num1} es primo")
    retur=True
            


def factorial ():
    resultFacto=0
    for x in range(1,num2+1):
        
        if resultFacto==0:
            resultFacto=x
        else:
            resultFacto=resultFacto*x
    print(f"El factorial de {num2} es {resultFacto}")


def palindrome ():
    palabrareves=""
    for i in palabra1:
        palabrareves=i+palabrareves

    if palabra1==palabrareves:
        print(f"La palabra {palabra1} es palindrome")
    else:
        print(f"La palabra {palabra1} no es palindrome")



opcion=1

while opcion>0 and opcion<4:
    print("-------------Menú-----------")
    print("1.- Número primo")
    print("2.- Factorial")
    print("3.- Palíndrome")
    print("4.- Salir")

    opcion=int(input("Seleccione una opción:  "))

    if opcion==1: 
        num1=int(input("Ingrese un número entre el 1 y el 15: "))
        NumPrimo()

    elif opcion==2:
        num2=int(input("Ingrese un número entre el 3 y el 10: "))
        factorial()
    elif opcion==3:
        palabra1=str(input("Ingrese una palabra: "))
        palindrome()
    
    elif opcion==4:
        print("-------------Saliendo-------------")

    else:
        print("Opción inválida, ingrese otra. ")
        opcion=1

import numpy as np 
from funciones import *
matriz_alumnos = np.empty((20,5),type(str))
indice = 0 #permitira controlar el numero de reg.igresados



llenar_celdas(matriz_alumnos)
indice = agregar_alumno(matriz_alumnos,indice)
indice= agregar_alumno(matriz_alumnos,indice)
listar_alumnos(matriz_alumnos)
buscar_alumnos(matriz_alumnos,'1')
certificado(matriz_alumnos,'2')
# menu principal
ciclo = True
while(ciclo):
    print('Menu Principal')
    print ('1) Ingresar Alumno')
    print ('2) Listar todos los alumno')
    print ('3) Buscar Alumno')
    print ('4) Certificado Alumno')
    print ('5) salir')
try:
    opcion= int(input('seleccione:'))
    if opcion==1:
        indice = agregar_alumno(matriz_alumnos,indice)
    if opcion==2:
        listar_alumnos(matriz_alumnos)
    if opcion==3:
        rut = input('ingrese rut a buscar:')
        buscar_alumnos(matriz_alumnos,rut)
    if opcion==4:
        rut = input('Ingrese rut del alumno:')
        certificado(matriz_alumnos,rut)
    if opcion==5:
        ciclo=False
except:
    print('ingreso mal el dato')

    #funciones------------------------------------------------------

    import random as rn

def listar_alumnos(matriz_alumnos):
    for f in range(20):
        fila=''
        for c in range(5):
            fila=fila+'|\t'+str(matriz_alumnos[f][c])
        print('|'+fila)
def llenar_celdas(matriz_alumnos):
    for f in range(20):
        for c in range(5):
            matriz_alumnos[f][c]='                       '
          

def agregar_alumno(matriz_alumnos, indice):

    rut = input('ingrese su rut: ')
    nombre = input('ingrese nombre: ')
    edad = input('ingrese edad: ')
    sexo = input('ingrese sexo: ')
    matriz_alumnos[indice][0] = indice + 1
    matriz_alumnos[indice][1] = rut
    matriz_alumnos[indice][2] = nombre
    matriz_alumnos[indice][3] = edad 
    matriz_alumnos[indice][4] = sexo
    indice = indice + 1

def buscar_alumnos(matriz_alumnos,rut):
    flag = False # no se encontro  
    for f in range(20):
        if matriz_alumnos[f][1]==rut:
            flag = True
            print('Encontro alumno')  
            print('Numero Reg:',f)
            print('Rut       :',matriz_alumnos[f][1])
            print('Nombre    :',matriz_alumnos[f][2])
            print('Edad      :',matriz_alumnos[f][3])
            print('sexo      :',matriz_alumnos[f][4])

    if flag==False:
        print('no se encontro')

def certificado(matriz_alumnos,rut):
    flag = False
    for f in range (20):
        if matriz_alumnos[f][1]==rut:'u'
            numero = rn.randint(1000,5000)
            print('------certificado alumnos regular------')
            print('numero:',numero)
            print(f'El señor(a): {matriz_alumnos[f][2]}')
            print('Es alumno regular del establecimiento')
            flag=True    
    if  flag == False:
        print ('no lo encontro')

import numpy as np
import funciones as fn

lista = [["tipo","patente","marca","precio","multa","fecharegistro","nombred"]]
opcion = 0
Matriz = np.array(lista)

while(opcion != 4):
    print("***** Bienvenido a Auto Seguro *****")
    print("1.- Grabar")
    print("2.- Buscar")
    print("3.- Imprimir Certificados")
    print("4.- Salir")
    try:
        opcion = int(input("Ingrese una opción: "))
        if (opcion == 1):
            lista2 = fn.grabar()
            Matriz = np.concatenate((Matriz,lista2), axis = 0)
        elif (opcion == 2):
            fn.buscar(Matriz)
        elif (opcion == 3):
            fn.imprimir(Matriz)
        elif (opcion == 4):
            print("Gracias por usar el Sistema (Versión 1.2)")
        else:
            print("Debe ingresar una opción del 1 al 4")
    except:
        print("Debe ingresar solo números")

-----------------------------FUNCIONES-------------------------------------

def grabar():
    
    cant = 0
    while(cant == 0):
        tipo = input("Ingrese tipo de vehiculo: ")
        cant = len(tipo)
        if(cant == 0):
            print("Debe ingresar el tipo de vehiculo")
    cant = 0
    patente = ""
    while(cant !=6):
        patente = input("Ingrese la patente, debe estar en formato AA1000/BBBB10: ")
        cant = len(patente)
        if (cant !=6):
            print("Patente no válida")
    
    cant = 0
    while(cant < 2 and cant > 15):
        marca = input("Ingrese marca del vehiculo: ")
        cant = len(marca)
        if(cant < 2 and cant > 15):
            print("Debe ingresar una marca entre 2 y 15 caracteres")

    precio = 0
    while(precio < 5000000):
        try:
            precio = int(input("Ingrese precio del producto: "))
            if(precio < 5000000):
                print("El precio debe ser mayor $5.000.000")
        except:
            print("Debe ingresar un número")
            precio = 0

    cant = 0
    while(cant == 0):
        multa = input("Ingrese monto y fecha de la multa del vehiculo: ")
        cant = len(multa)
        if(cant == 0):
            print("Debe ingresar datos válidos")
            

    cant = 0
    while(cant == 0):
        fecharegistro = input("Ingrese la fecha de registro del vehiculo: ")
        cant = len(fecharegistro)
        if(cant == 0):
            print("Debe ingresar datos válidos")

    cant = 0
    while(cant ==0):
        nombred = input("Ingrese el nombre del dueño del vehiculo: ")
        cant = len(nombred)
        if(cant ==0):
            print("Debe ingresar datos válidos")
    
    
    lista = [[tipo,patente,marca,str(precio),multa,fecharegistro,nombred]]

    return lista


def buscar(Matriz):
    cant = 0
    while(cant != 6):
        patente = input("Ingrese Patente para buscar: ")
        cant = len(patente)
        if(cant != 6):
            print("Debe ingresar una patente valida")
    
    filas, columnas = Matriz.shape
    existe = False
    encontrada = 0
    for fi in range(filas):
        if(Matriz[fi][1] == patente):
            existe = True
            encontrada = fi

    if(existe):
        if Matriz[encontrada][1] == patente:
            print(f"Tipo vehiculo: {Matriz[encontrada][0]}")
            print(f" patente: {Matriz[encontrada][1]}")
            print(f"marca: {Matriz[encontrada][2]}")
            print(f"precio: {Matriz[encontrada][3]}")
            print(f" multas : {Matriz[encontrada][4]}")
            print(f"fecha registro: {Matriz[encontrada][5]}")
            print(f"nombre dueño : {Matriz[encontrada][6]}")
        else:
            print("No existe patente")
    else:
        print("Patente no registrada")

def imprimir(Matriz):
    filas,columnas = Matriz.shape
    f=False
    for f in range(filas):
        for c in range(columnas):
            emision=input("Ingrese patente para generar certificado: \n")
            if emision ==Matriz[1]:
                anotaciones=input("Ingrese anotaciones: ")
                mult2=int(input("Ingrese multas :\n"))
                print(f"Anotaciones: {anotaciones}\n Multas: {mult2}")
                f=True
        else:
            print("Patente no encontrada")

import funcionesAvion as fun

asientosCom=[]
asientosAvion=fun.crearAvionInicial()
clientes=[]


op=1
while op >0 and op <5:
    print(f"1.-Ver asientos disponibles")
    print(f"2.-Comprar asiento")
    print(f"3.-Anular vuelo")
    print(f"4.-Modificar datos de pasajero")
    print(f"5.-Salir")
        
    op=int(input("Selecione una opcion\n"))
        
    if op==1:
        fun.mostrarAsientosDisponibles(asientosCom,asientosAvion)
    elif op==2:
        asientoComprar = int(input("Ingrese el asiento que desea comprar\n"))
        if fun.validarAsientoDisponible(asientoComprar,asientosCom):
            cliente=fun.pedirDatosAlUsuario(asientoComprar)
             #guarda el cliente en la lista llamada Clientes. 
            clientes.append(cliente)
       
             #mostrar el precio del asiento
            fun.obtenerValorAsiento(asientoComprar,cliente[3])
            
            #guardar en mi lista de asientos comprados
            asientosCom.append(asientoComprar)
            
            print("El asiento se a comprado exitosamente")
             
        else:
            print("El asiento que ingreso no esta disponible")    
        
    elif op==3:
        print(clientes)
        asientoAnular=int(input("Ingrese el asiento que desea anular\n"))
        
        asientosCom.remove(asientoAnular)
        for cli in clientes:
            if cli[4]==asientoAnular:
                clientes.remove(cli)
            print("Cliente Eliminado")
            
        print(clientes)
    elif op==4:
        
        asientoModificar=int(input("Ingrese el numero de asiento\n"))
        rutModificar=input("Ingrese el rut del pasajero")
        
        for c in clientes:
            if c[4]==asientoModificar and c[1]==rutModificar:
                print("---Ingrese Datos a Modificar---")
                
                nuevoNombre=input("Ingrese el nuevo nombre")
                nuevoTelefono=int(input("Ingrese su nuevo telefono"))
                
                c[0]=nuevoNombre
                c[2]=nuevoTelefono
                
                print("Datos Modificados Exitosamente")
        print(clientes)        
        
    elif op==5:
        print("Saliendo.......")
    else:
        print("Opcion Invalida")
        


-----------------------------------FUNCIONES---------------------------------------------

import numpy as np


def crearAvionInicial():
    asientosAvion=np.zeros((7,6))
    correlativo=1
    for x in range(len(asientosAvion)):
        for i in range(len(asientosAvion[x])):
            asientosAvion[x,i]=correlativo
            correlativo=correlativo+1  
    return asientosAvion
 
 
 
def mostrarAsientosDisponibles(asientosComprados, asientosAvion):
    for x in range(len(asientosAvion)):
        linea = ''
        for i in range(len(asientosAvion[x])):
            asiento = asientosAvion[x,i]
            if asiento in asientosComprados:
                linea = linea + ' X - '
            else:
                linea = linea + str(int(asiento)) + ' - '
        print(linea)
      
 
def validarAsientoDisponible(asientoComprar, asientosComprados ):
    if asientoComprar in asientosComprados:
        return False
    else:
        return True
 
 
def pedirDatosAlUsuario(asiento):
    usuario=[]
    nombre=input("Ingrese su nombre\n")
    rut=int(input("Ingrese su Rut\n"))
    telefono=int(input("Ingrese su numero Telefonico\n"))
    banco=input("Ingrese su Banco\n")
    
    usuario.append(nombre) #0
    usuario.append(rut) #1
    usuario.append(telefono) #2
    usuario.append(banco) #3
    usuario.append(usuario) #4
    
    return usuario


def obtenerValorAsiento(numAsiento,tipoBanco):
    asientosVip=np.array([i for i in range(31,42)])
    precioAsiento=0
    if numAsiento in asientosVip:
        precioAsiento=240000
    else:
        precioAsiento=78900
        
    if tipoBanco =="BancoDuoc":
        print(f"El precio final: {precioAsiento - precioAsiento * 0.15} ")
    else:
        print(f"El precio del asiento es: {precioAsiento}")

#ARREGLO BIDIMENSIONALES
#PYTHON NO POSEE ESTRUCTURAS PROPIAS PARA DEFINIR MATRICES, SINO MAS BIEN SON LISTAS SOBRE LISTAS.

#CASO 1
print("crear matriz  - caso 1")
import numpy as np
matriz = np.array([[0,1,2], [3,4,5]])
for f in range(2):
    for c in range (3):
     print(matriz[f][c])


#caso 2 (usando listas)
print("crear matriz, usando listas")
lista = [[1,2,3],[4,5,6]]
matriz = np.array(lista)
print(matriz) 


#mostrar un elemento de la matriz 
print("mostrar un elemento de la matriz")
#caso 1
print("caso 1")

matriz = np.array([[0,1,2], [3,4,5]])
for f in range (2):
    for c in range(3):
        print(matriz[f][c])
print("")
print(matriz[1,1])


#caso 2
print("caso 2")
lista = [[1,2,3], [4,5,6]]
matriz = np.array(lista)
print(matriz[0][1])

#operaciones con arreglos de dos dimensiones.
print("mostrar un elemento de la matriz")

lista = [[1,2,3],[4,5,6]]
print(lista)# [[1, 2, 3], [4, 5, 6]]

matriz = np.array(lista)
print(matriz[1,1])# 5

print(matriz[:,2])#[3 6]

print(matriz[0,:])#[1 2 3]

print(matriz[0,::-1])#[3 2 1]

#generar matriz
print("generar matriz")

matriz = np.zeros((3,3))#gnera matriz con 0.
print(matriz)
'''[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]'''

matriz = np.ones((3,3))#genera matriz con unos.
print(matriz)
''' [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]'''

matriz = np.diag([1,1,1])#genera matriz con diagonal principal con 1.
print(matriz)
'''[[1 0 0]
    [0 1 0]
    [0 0 1]]'''


lista = [[1,2,3],[4,5,6]]#
matriz = np.array(lista)
print(matriz.sum())#se le indica sumar con sum , todos los elementos del arreglo.


lista = [[1,2,3],[4,5,6]]
matriz = np.array(lista)
print(matriz)
'''[[1 2 3]
    [4 5 6]]'''
print("suma elementos fila 0 : ", matriz[0,:].sum())# 6 (1+2+3 =6)
print("suma elementos fila 1 : ", matriz[1,:].sum())#15 (4+5+6= 15)

matriz = np.array([[0,1,2],[3,4,5]])
print(matriz.ndim) #muestra las dimensiones del arreglo o matriz.

matriz = np.array([[0,1,2],[3,4,5]])
print(matriz.shape)# muestra la estructura de la matriz (2,3) 2 filas por 3 columnas.
print(matriz)
'''[[0 1 2]
    [3 4 5]]'''

matriz = np.array([[0,1,2],[3,4,5]])
print(matriz.size) # 6 , muestra la cantidad de numeros??

#concatenar 2 matrices (2 dimensiones)

n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[10,20,30],[40,50,60]])
np.concatenate((n1,n2), axis = 0)
print()

--------------------------------------MAIN--------------------------------------------------
from funciones import grabar,buscar,imprimir
import os
os.system("cls");
op1=1
op2=0
while op1==1:

   print("|-------------------------|");
   print("|  Opcion 1  |  Grabar    |");
   print("|  Opcion 2  |  Buscar    |");
   print("|  Opcion 3  |  Imprimir  |");
   print("|  Opcion 4  |  Salir     |");
   print("|-------------------------|");
   op2=int(input("ingrese una opcion: "));
   if(op2==1):
       grabar();
   if(op2==2):
       buscar();
   if(op2==3):
       imprimir();



------------------------------------FUNCIONES-----------------------------------------------


from ast import Num
from operator import truediv
import numpy as np

nronif=[];
nombrenif=[];
lisedadnif=[];
arreglo=[]
opc=1
opc2=0
#grabar
def grabar():
    nif=str(input("Ingrese su NIF: "));
    nronif.append(nif);
    nombre=str(input("Ingrese su nombre Minimo 8 caracteres: "));
    nombrenif.append(nombre)   
    edadnif=int(input("Ingrese su edad debe ser >=0: "));
    if(edadnif>=0 and edadnif<=110):
        lisedadnif.append(edadnif);
        print("Los datos han sido ingresados de manera correcta")
        print("----------------")
    else:
        print("La edad ingresada no es correcta, Intentelo nuevamente")
        

#buscar
def buscar():
    nifbus=input("ingrese el NIF de la persona que desea buscar: ");
    bandera4=False
    print()
    for r in range(len(nronif)):
        if nifbus==nronif[r]:
            v_posicion=r
            bandera4=True
    if(bandera4==True):
        print("El NIF es:",nronif[v_posicion])
        print("El nombre es:",nombrenif[v_posicion])
        print("La edad es:",lisedadnif[v_posicion])
        print("Esta persona pertenece a la Union Europea")

#Imprimir
def imprimir():
    buscarnif=input("ingrese el NIF de la persona que desea buscar: ");
    bandera5=False
    print()
    for m in range(len(nronif)):
        if buscarnif==nronif[m]:
            v_posicion=m
            bandera5=True
    if(bandera5==True):
        while opc==1:
            print("Que tipo de certificado necesita")
            print("1) CERTIFICADO DE NACIMIENTO")
            print("2) ESTADO CONYUGAL")
            print("3) PERTENENCIA A LA UNION EUROPEA")
            print("4) VOLVER AL MENU")
            opc2=int(input());
            if(opc2==1):
                print("El certificado de nacimiento es el siguiente")
                print("El NIF es:",nronif[v_posicion])
                print("El nombre es:",nombrenif[v_posicion])
                print("La edad es:",lisedadnif[v_posicion])
                print("El precio es de $1.000")

import funciones as fun

opcion=1

while opcion>0 and opcion<5:
    print("----------MENÚ----------")
    opcion=int(input("1.- Grabar usuario \n2.- Buscar \n3.- Imprimir certificado\n4.- Salir\nSeleccione opción: "))

    if opcion==1: 
        fun.grabar()

    if opcion==2:
        fun.buscar()

    if opcion==3:
        fun.impresion()

    if opcion==4:
        
        print("Saliendo...")
        exit()

#FUNCIONES

listanif=[]
listanomb=[]
listaedad=[]
listaunion=[]


def grabar(): 
    nif=input("Ingrese su NIF: ")
    listanif.append(nif)

    flagdatocorrecto=False
    while flagdatocorrecto==False:
        try:
            nomb=input("Ingrese su nombre completo: ")
            listanomb.append(nomb)
        except:
            print("nombre incorrecto.")
        else: 
            if len(nomb)>=8:
                flagdatocorrecto=True
            else:
                print("Nombre incorrecto, ingrese nuevamente.")
    

    flagdatocorrecto=False
    while flagdatocorrecto==False:
        try:
            edad=int(input("Ingrese su edad: "))
            listaedad.append(edad) 
        except:
            print("Edad incorrecta.")
        else: 
            if edad>=0:
                flagdatocorrecto=True
                print("...................................")
                print(".....USUARIO CREADO CON ÉXITO......")
            else:
                print("Edad inválida, ingrese nuevamente.")
    

def buscar():
    nif2=input("Ingrese NIF a consultar: ")

    if nif2 in listanif:

        for i in range(len(listanif)):
            if nif2==listanif[i]:
                print("--------DATOS CIUDADANO--------")
                print(f"Nombre: {listanomb[i]} \nNIF: {listanif[i]} \nEdad: {listaedad[i]}")
            
    else:
        print("NIF inválido, ingrese nuevamente.")



def impresion():

    impresion=1 
    while impresion>0 and impresion<4:
        print("----------CERTIFICADOS----------")

        impresion=int(input("1.-Certificado de nacimiento\n2.-Certificado estado conyugal\n3.-Certificado pertenencia unión European\n4.-Volver al menú\nSeleccione una opción: "))
        

        if impresion==1: 
            nif3=input("Ingrese su NIF: ")
            if nif3 in listanif:
                for i in range(len(listanif)):
                    if nif3==listanif[i]:
                        print("--------CERTIFICADO NACIMIENTO--------")
                        print(f"Nombre: {listanomb[i]} \nNIF: {listanif[i]} \nEdad: {listaedad[i]}n\Esta persona pertenece a la Union Europea")

            else:
                print("NIF inválido, ingrese nuevamente.")
            
        if impresion==2: 
            nif3=input("Ingrese su NIF: ")
            if nif3 in listanif:
                for i in range(len(listanif)):
                    if nif3==listanif[i]:
                        print("--------CERTIFICADO ESTADO CONYUGAL--------")
                        print(f"Nombre: {listanomb[i]} \nNIF: {listanif[i]}")
            else:
                print("NIF inválido, ingrese nuevamente.")                

        if impresion==3: 
            nif3=input("Ingrese su NIF: ")
            if nif3 in listanif:
                for i in range(len(listanif)):
                    if nif3==listanif[i]:
                        print("--------CERTIFICADO PERTENENCIA UNIÓN EUROPEA--------")
                        print(f"Nombre: {listanomb[i]} \nNIF: {listanif[i]}n\Pertenenciente a la unión Europea")
            else:
                print("NIF inválido, ingrese nuevamente.")    

        if impresion==4: 
            print("Volviendo al menú...")